# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - oddapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_47DC5CAA974349D197A019E7E03FB8D5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9F4C6ED68C7748D986D3ED9DEF2F1FC1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CA78C2BBB4844AC4953A75D395FB7A53 }}

      - name: Get Key Vault Secret
        uses: Azure/get-keyvault-secrets@v1
        id: mySecrets # ID for this step to reference its outputs
        with:
          keyvault: 'oddkv' # Replace with your Azure Key Vault name
          secrets: 'ODDAPP-OPENAI-API-KEY' # Replace with the name of the secret to retrieve

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'oddapp'
          slot-name: 'Production'
        env:
          MY_APP_SETTING: ${{ secrets.MY_GITHUB_SECRET }}

      - name: Use the retrieved secret
        run: echo "The secret value is: ${{ steps.mySecrets.outputs.ODDAPP-OPENAI-API-KEY }}"
        
      #- name: Get Secrets from Key Vault
        #id: fetch-secrets
        #run: |
        #secret_value=$(az keyvault secret show --name <YOUR_SECRET_NAME> --vault-name ${{ secrets.KEY_VAULT_NAME }} --query value -o tsv)
        #echo "::set-output name=secret::${secret_value}"

      #- name: Use Secrets
        #run: |
        #echo "The secret is: ${{ steps.fetch-secrets.outputs.secret }}"
        # Add your deployment commands here, using the secret as needed
